IF OBJECT_ID(N'upvotes', N'U') IS NULL
BEGIN
  CREATE TABLE upvotes (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    report_id INTEGER NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    PRIMARY KEY (user_id, report_id)
  );
END;
